name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '25.1.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Strato
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STRATO_SERVER }}
          username: ${{ secrets.STRATO_USERNAME }}
          key: ${{ secrets.STRATO_SSH_KEY }}
          port: 22
          source: '.next/**'
          target: '/'  # Adjust the remote directory as needed